Repository MASSHUU12/ipz, pull requests merged in 2025-05, with the labels that each got.

#207 refactor(frontend): improve responsiveness & rewrite dashboard
  .prettierrc.json
  resources/js/data/cities.ts
  resources/js/data/useAirQuality.ts
  resources/js/data/useWeatherConditions.ts
  resources/js/pages/components/AirQualityBar.tsx
  resources/js/pages/dashboard.tsx
  resources/js/pages/dashboard/AirPollutionChart.tsx
  resources/js/pages/dashboard/CityMap.tsx
  resources/js/pages/dashboard/Dashboard.tsx
  resources/js/pages/dashboard/SearchAppBar.tsx
  resources/js/pages/dashboard/WeatherCard.tsx
  resources/js/pages/mapUpdater.tsx
  resources/js/utils/airQuality.ts
  routes/web.php
Labels: enhancement

#211 404 - notFound
  resources/views/errors/404.blade.php
Labels: enhancement, sprint6, sprint7

#222 feat(backend): favorite locations
  app/Http/Controllers/UserFavoriteLocationsController.php
  app/Http/Requests/StoreFavoriteLocationRequest.php
  app/Http/Requests/UpdateFavoriteLocationRequest.php
  app/Models/User.php
  app/Models/UserFavoriteLocation.php
  database/migrations/2025_05_03_115928_create_user_favorite_locations_table.php
  docs/api/bruno/Favorite locations/Delete Location.bru
  docs/api/bruno/Favorite locations/Get Location.bru
  docs/api/bruno/Favorite locations/Get Locations.bru
  docs/api/bruno/Favorite locations/Patch Location.bru
  docs/api/bruno/Favorite locations/Post Location.bru
  docs/api/bruno/Favorite locations/folder.bru
  docs/api/favorite_locations_endpoints.yml
  routes/api.php
Labels: documentation, enhancement, sprint7

#239 BE
  app/Http/Requests/GetAirQualityRequest.php
  bootstrap/app.php
  resources/js/pages/dashboard/SearchAppBar.tsx
Labels: enhancement

#256 chore: run tests on PR only when necessary
  .github/workflows/run_phpunit_tests.yml
  .github/workflows/run_playwright_tests.yml
Labels: enhancement, sprint8

#258 feat(backend): proper password update
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/LoginRequest.php
  app/Http/Requests/RegisterRequest.php
  app/Http/Requests/UpdatePasswordRequest.php
  docs/api/auth_endpoints.yml
  docs/api/bruno/Auth/Login.bru
  docs/api/bruno/User/Patch User.bru
  docs/api/bruno/User/Update Password.bru
  docs/api/user_endpoints.yml
  routes/api.php
Labels: documentation, enhancement, sprint8

#262 feat(backend): use synoptic historical data in the ImgwController
  app/Http/Controllers/ImgwController.php
Labels: enhancement, sprint8

#264 feat(backend): try fuzzy-matching against station names
  app/Http/Controllers/ImgwController.php
Labels: enhancement, sprint8

#289 fix(backend): exception when logging on nonexistent account
  app/Http/Controllers/AuthController.php
Labels: enhancement, sprint8

#301 fix(backend): /air-quality returns 404 when db is empty
  app/Http/Requests/GetAirQualityRequest.php
Labels: bug, sprint9

#306 fix(frontend): measurements are not correctly parsed
  resources/js/api/airQualityApi.ts
  resources/js/pages/dashboard/AirPollutionChart.tsx
Labels: bug, sprint9

#313 feat(backend): invalidate all user tokens after password change
  app/Http/Controllers/AuthController.php
  docs/api/auth_endpoints.yml
Labels: documentation, enhancement, sprint9

#318 fix(frontend): black bars in an air pollution chart
  resources/js/pages/dashboard/AirPollutionChart.tsx
  resources/js/utils/airQuality.ts
Labels: bug, sprint10

#309 Frontend
  resources/js/api/leaderboardApi.ts
  resources/js/pages/EditProfile.tsx
  resources/js/pages/airQualityRanking.tsx
  resources/js/pages/dashboard/Dashboard.tsx
Labels: enhancement, sprint9, sprint10
